import { PrismaClient, EnergyLevel, Location, Cost, Social } from '@prisma/client';

const prisma = new PrismaClient();

const activities = [
  // LOW ENERGY - HOME - SOLO
  {
    title: 'Meditasyon Seansı',
    category: 'wellness',
    tags: ['meditasyon', 'rahatlama', 'mindfulness'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'anxious', 'tired'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Rahat bir pozisyon bul', 'Gözlerini kapat', 'Nefesine odaklan', '10 dakika boyunca derin nefes al'],
    safetyNotes: null,
    url: 'https://www.headspace.com/meditation',
  },
  {
    title: 'Podcast Dinle',
    category: 'entertainment',
    tags: ['podcast', 'dinleme', 'öğrenme'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'curious', 'relaxed'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['İlgi alanına göre podcast seç', 'Rahat bir yere otur', 'Kulaklıklarını tak', 'Dinlemeye başla'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Kitap Oku',
    category: 'education',
    tags: ['okuma', 'kitap', 'öğrenme'],
    durationMin: 15,
    durationMax: 120,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'curious', 'relaxed'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Okuyacağın kitabı seç', 'Rahat bir köşe bul', 'Çay/kahve hazırla', 'Okumaya başla'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'YouTube Belgesel İzle',
    category: 'entertainment',
    tags: ['video', 'belgesel', 'öğrenme'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'curious'],
    location: Location.home,
    cost: Cost.free,
    social: Social.both,
    steps: ['İlgi alanına göre belgesel seç', 'Atıştırmalık hazırla', 'Rahata geç', 'İzlemeye başla'],
    safetyNotes: null,
    url: 'https://www.youtube.com/results?search_query=documentary',
  },
  {
    title: 'Günlük Yaz',
    category: 'wellness',
    tags: ['yazma', 'günlük', 'self-care'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'anxious', 'thoughtful'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Defter ve kalem al', 'Bugün neler hissettiğini düşün', 'Düşüncelerini yaz', 'Minnettar olduğun 3 şeyi yaz'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Puzzle Çöz',
    category: 'hobby',
    tags: ['puzzle', 'bulmaca', 'zeka'],
    durationMin: 20,
    durationMax: 90,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'focused'],
    location: Location.home,
    cost: Cost.low,
    social: Social.solo,
    steps: ['Puzzle seç', 'Masayı hazırla', 'Kenar parçalarından başla', 'Sabırla devam et'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Cilt Bakımı Rutini',
    category: 'self-care',
    tags: ['cilt bakımı', 'self-care', 'güzellik'],
    durationMin: 15,
    durationMax: 45,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'tired', 'self-care'],
    location: Location.home,
    cost: Cost.low,
    social: Social.solo,
    steps: ['Yüzünü temizle', 'Maske uygula', '15 dakika bekle', 'Nemlendirici sür'],
    safetyNotes: null,
    url: null,
  },

  // MEDIUM ENERGY - HOME
  {
    title: 'Yemek Pişir',
    category: 'cooking',
    tags: ['yemek', 'mutfak', 'yaratıcılık'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'hungry', 'bored'],
    location: Location.home,
    cost: Cost.low,
    social: Social.both,
    steps: ['Tarif seç', 'Malzemeleri hazırla', 'Adım adım tarifi takip et', 'Sunumu güzelleştir'],
    safetyNotes: 'Sıcak yüzeylerden uzak dur',
    url: null,
  },
  {
    title: 'Ev Egzersizi - Yoga',
    category: 'fitness',
    tags: ['yoga', 'egzersiz', 'esneme'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.medium,
    moodTags: ['stressed', 'stiff', 'tired'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Yoga matı ser', 'YouTube yoga videosu aç', 'Nefes egzersizleriyle başla', 'Pozları takip et'],
    safetyNotes: 'Aşırı zorlama yapma',
    url: 'https://www.youtube.com/results?search_query=yoga+for+beginners',
  },
  {
    title: 'Resim Çiz veya Boya',
    category: 'art',
    tags: ['resim', 'sanat', 'yaratıcılık'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'bored', 'relaxed'],
    location: Location.home,
    cost: Cost.low,
    social: Social.solo,
    steps: ['Malzemeleri hazırla', 'Konu seç veya serbest çiz', 'Müzik aç', 'Yaratmaya başla'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Ev Temizliği',
    category: 'productivity',
    tags: ['temizlik', 'organizasyon', 'düzen'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['productive', 'stressed', 'energetic'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Hangi odayla başlayacağını seç', 'Müzik aç', 'Yüzeylerden başla', 'Organize et'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Online Kurs İzle',
    category: 'education',
    tags: ['eğitim', 'online kurs', 'öğrenme'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['curious', 'productive', 'bored'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Öğrenmek istediğin konuyu seç', 'Udemy/Coursera aç', 'Not defteri hazırla', 'Dersi takip et'],
    safetyNotes: null,
    url: 'https://www.udemy.com',
  },
  {
    title: 'Video Oyunu Oyna',
    category: 'entertainment',
    tags: ['oyun', 'gaming', 'eğlence'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['bored', 'competitive', 'stressed'],
    location: Location.home,
    cost: Cost.free,
    social: Social.both,
    steps: ['Oyun seç', 'Konsolu/PC aç', 'Rahat otur', 'Eğlenmeye başla'],
    safetyNotes: 'Uzun süre oynama, ara ver',
    url: null,
  },
  {
    title: 'Enstrüman Çal',
    category: 'music',
    tags: ['müzik', 'enstrüman', 'yaratıcılık'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'bored', 'relaxed'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Enstrümanını al', 'Akort et', 'Isınma egzersizi yap', 'Sevdiğin parçayı çal'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Dans Et',
    category: 'fitness',
    tags: ['dans', 'egzersiz', 'eğlence'],
    durationMin: 15,
    durationMax: 45,
    energyLevel: EnergyLevel.medium,
    moodTags: ['happy', 'energetic', 'bored'],
    location: Location.home,
    cost: Cost.free,
    social: Social.both,
    steps: ['Favori müziğini aç', 'Salon ortasına geç', 'Ritme kapıl', 'Eğlen!'],
    safetyNotes: null,
    url: null,
  },

  // HIGH ENERGY - HOME
  {
    title: 'HIIT Antrenmanı',
    category: 'fitness',
    tags: ['hiit', 'egzersiz', 'kardiyo'],
    durationMin: 15,
    durationMax: 45,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'stressed', 'motivated'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Spor kıyafetlerini giy', 'HIIT videosu aç', 'Isınma yap', 'Yüksek tempoda antrenman'],
    safetyNotes: 'Düzgün form koru, fazla zorlama',
    url: 'https://www.youtube.com/results?search_query=hiit+workout',
  },
  {
    title: 'Ev Partisi Hazırlığı',
    category: 'social',
    tags: ['parti', 'sosyal', 'eğlence'],
    durationMin: 60,
    durationMax: 180,
    energyLevel: EnergyLevel.high,
    moodTags: ['social', 'excited', 'happy'],
    location: Location.home,
    cost: Cost.medium,
    social: Social.friends,
    steps: ['Arkadaşları davet et', 'Atıştırmalıklar hazırla', 'Müzik listesi oluştur', 'Evi süsle'],
    safetyNotes: null,
    url: null,
  },

  // LOW ENERGY - OUTDOOR
  {
    title: 'Parkta Yürüyüş',
    category: 'outdoor',
    tags: ['yürüyüş', 'doğa', 'rahatlama'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'bored', 'thoughtful'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Rahat ayakkabı giy', 'Yakındaki parka git', 'Yavaşça yürü', 'Doğayı gözlemle'],
    safetyNotes: 'Hava durumunu kontrol et',
    url: null,
  },
  {
    title: 'Kahve Dükkanında Otur',
    category: 'social',
    tags: ['kahve', 'sosyal', 'rahatlama'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.low,
    moodTags: ['social', 'bored', 'relaxed'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Favori kahve dükkanını seç', 'Güzel bir köşe bul', 'İçeceğini sipariş et', 'Kitap oku veya insanları izle'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Fotoğraf Çekimi',
    category: 'hobby',
    tags: ['fotoğraf', 'sanat', 'yaratıcılık'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.low,
    moodTags: ['creative', 'curious', 'relaxed'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Telefon/kamera al', 'İlginç lokasyon seç', 'Farklı açılar dene', 'En iyileri düzenle'],
    safetyNotes: null,
    url: null,
  },

  // MEDIUM ENERGY - OUTDOOR
  {
    title: 'Bisiklet Turu',
    category: 'fitness',
    tags: ['bisiklet', 'spor', 'outdoor'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['energetic', 'adventurous', 'bored'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Bisikletini hazırla', 'Rota planla', 'Su şişesi al', 'Pedal çevirmeye başla'],
    safetyNotes: 'Kask tak, trafik kurallarına uy',
    url: null,
  },
  {
    title: 'Piknik Yap',
    category: 'social',
    tags: ['piknik', 'outdoor', 'yemek'],
    durationMin: 60,
    durationMax: 180,
    energyLevel: EnergyLevel.medium,
    moodTags: ['social', 'relaxed', 'happy'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.friends,
    steps: ['Piknik sepeti hazırla', 'Battaniye al', 'Parka git', 'Yiyecekleri ser ve tadını çıkar'],
    safetyNotes: 'Çöpleri topla',
    url: null,
  },
  {
    title: 'Müze Ziyareti',
    category: 'culture',
    tags: ['müze', 'sanat', 'tarih'],
    durationMin: 60,
    durationMax: 180,
    energyLevel: EnergyLevel.medium,
    moodTags: ['curious', 'cultural', 'bored'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Ziyaret etmek istediğin müzeyi seç', 'Bilet al', 'Rahat ayakkabı giy', 'Sergileri gez'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Bowling Oyna',
    category: 'entertainment',
    tags: ['bowling', 'spor', 'eğlence'],
    durationMin: 60,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['social', 'competitive', 'bored'],
    location: Location.outdoor,
    cost: Cost.medium,
    social: Social.friends,
    steps: ['Arkadaşlarını topla', 'Bowling salonuna git', 'Oyun başlat', 'Eğlen!'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Sinema',
    category: 'entertainment',
    tags: ['film', 'sinema', 'eğlence'],
    durationMin: 90,
    durationMax: 180,
    energyLevel: EnergyLevel.medium,
    moodTags: ['bored', 'relaxed', 'social'],
    location: Location.outdoor,
    cost: Cost.medium,
    social: Social.both,
    steps: ['Vizyondaki filmlere bak', 'Bilet al', 'Patlamış mısır al', 'Filmin tadını çıkar'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Alışveriş Merkezi Gezisi',
    category: 'shopping',
    tags: ['alışveriş', 'gezinti', 'sosyal'],
    durationMin: 60,
    durationMax: 180,
    energyLevel: EnergyLevel.medium,
    moodTags: ['bored', 'social', 'shopping'],
    location: Location.outdoor,
    cost: Cost.medium,
    social: Social.both,
    steps: ['AVM seç', 'Vitrinleri gez', 'Kahve molası ver', 'İstersen alışveriş yap'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Botanik Bahçesi Gezisi',
    category: 'outdoor',
    tags: ['doğa', 'botanik', 'fotoğraf'],
    durationMin: 60,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['relaxed', 'curious', 'nature'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Yakındaki botanik bahçesini bul', 'Rahat ayakkabı giy', 'Bitkileri keşfet', 'Fotoğraf çek'],
    safetyNotes: null,
    url: null,
  },

  // HIGH ENERGY - OUTDOOR
  {
    title: 'Koşu',
    category: 'fitness',
    tags: ['koşu', 'spor', 'kardiyo'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'stressed', 'motivated'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Spor kıyafetlerini giy', 'Isınma yap', 'Rota belirle', 'Koşmaya başla'],
    safetyNotes: 'Aşırı zorlama yapma, su iç',
    url: null,
  },
  {
    title: 'Yüzme',
    category: 'fitness',
    tags: ['yüzme', 'spor', 'su'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'hot', 'stressed'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Mayo/şort al', 'Havuza git', 'Duş al', 'Yüzmeye başla'],
    safetyNotes: 'Havuz kurallarına uy',
    url: null,
  },
  {
    title: 'Doğa Yürüyüşü (Hiking)',
    category: 'outdoor',
    tags: ['hiking', 'doğa', 'macera'],
    durationMin: 90,
    durationMax: 300,
    energyLevel: EnergyLevel.high,
    moodTags: ['adventurous', 'nature', 'energetic'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Parkur seç', 'Bot ve sırt çantası hazırla', 'Su ve atıştırmalık al', 'Doğayı keşfet'],
    safetyNotes: 'Hava durumu kontrol et, birini bilgilendir',
    url: null,
  },
  {
    title: 'Basketbol Oyna',
    category: 'sports',
    tags: ['basketbol', 'spor', 'takım'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'competitive', 'social'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.friends,
    steps: ['Top al', 'Saha bul', 'Takım kur', 'Oyna!'],
    safetyNotes: 'Isınma yap',
    url: null,
  },
  {
    title: 'Futbol Oyna',
    category: 'sports',
    tags: ['futbol', 'spor', 'takım'],
    durationMin: 45,
    durationMax: 120,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'competitive', 'social'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.friends,
    steps: ['Top ve krampon al', 'Saha bul', 'Takımları kur', 'Maç başlasın!'],
    safetyNotes: 'Isınma ve soğuma yap',
    url: null,
  },
  {
    title: 'Tırmanış Duvarı',
    category: 'adventure',
    tags: ['tırmanış', 'macera', 'spor'],
    durationMin: 60,
    durationMax: 120,
    energyLevel: EnergyLevel.high,
    moodTags: ['adventurous', 'challenging', 'energetic'],
    location: Location.outdoor,
    cost: Cost.medium,
    social: Social.both,
    steps: ['Tırmanış merkezine git', 'Ekipman kirala', 'Eğitmen brifingi al', 'Duvara tırman'],
    safetyNotes: 'Güvenlik ekipmanlarını kontrol et',
    url: null,
  },
  {
    title: 'Kaykay/Paten',
    category: 'sports',
    tags: ['kaykay', 'paten', 'sokak'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'adventurous', 'free'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Kaykay/paten al', 'Koruyucu ekipman tak', 'Uygun alan bul', 'Pratik yap'],
    safetyNotes: 'Kask ve koruyucu tak',
    url: null,
  },

  // ANY LOCATION OPTIONS
  {
    title: 'Arkadaşla Telefonda Sohbet',
    category: 'social',
    tags: ['sohbet', 'sosyal', 'arkadaş'],
    durationMin: 15,
    durationMax: 60,
    energyLevel: EnergyLevel.low,
    moodTags: ['lonely', 'bored', 'social'],
    location: Location.any,
    cost: Cost.free,
    social: Social.friends,
    steps: ['Arayacağın arkadaşı seç', 'Ara', 'Sohbet et', 'Plan yap'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Dil Öğren (Duolingo)',
    category: 'education',
    tags: ['dil', 'öğrenme', 'uygulama'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.low,
    moodTags: ['productive', 'curious', 'bored'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Duolingo aç', 'Günlük dersini yap', 'Yeni kelimeler öğren', '5 dakika pratik'],
    safetyNotes: null,
    url: 'https://www.duolingo.com',
  },
  {
    title: 'Sudoku/Bulmaca Çöz',
    category: 'puzzle',
    tags: ['sudoku', 'bulmaca', 'zeka'],
    durationMin: 10,
    durationMax: 45,
    energyLevel: EnergyLevel.low,
    moodTags: ['focused', 'bored', 'relaxed'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Bulmaca uygulaması aç', 'Zorluk seviyesi seç', 'Çözmeye başla', 'Beynini çalıştır'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Nefes Egzersizleri',
    category: 'wellness',
    tags: ['nefes', 'rahatlama', 'mindfulness'],
    durationMin: 5,
    durationMax: 20,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'anxious', 'tired'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Rahat otur', '4-7-8 tekniğini uygula', '4 saniye nefes al', '7 saniye tut, 8 saniye ver'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Stretching/Germe',
    category: 'fitness',
    tags: ['germe', 'esneme', 'egzersiz'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.medium,
    moodTags: ['stiff', 'tired', 'stressed'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Uygun alan bul', 'Boyun ve omuz germeleriyle başla', 'Bacak ve sırt ger', 'Her pozisyonu 30 sn tut'],
    safetyNotes: 'Aşırı zorlama',
    url: null,
  },

  // ─── EK AKTİVİTELER ───

  // LOW ENERGY - HOME
  {
    title: 'Playlist Oluştur',
    category: 'music',
    tags: ['müzik', 'playlist', 'keşfet'],
    durationMin: 15,
    durationMax: 45,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'relaxed', 'creative'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Spotify/YouTube Music aç', 'Bir tema belirle (chill, enerjik vb.)', 'Şarkıları keşfet ve ekle', 'Playlistine isim ver'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Çay/Kahve Seremonisi',
    category: 'self-care',
    tags: ['çay', 'kahve', 'rahatlama'],
    durationMin: 15,
    durationMax: 30,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'tired', 'relaxed'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Favori çayını/kahveni seç', 'Suyu kaynat', 'Güzel bir fincan seç', 'Yavaşça demle ve tadını çıkar'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'TED Talk İzle',
    category: 'education',
    tags: ['ted', 'ilham', 'öğrenme'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.low,
    moodTags: ['curious', 'motivated', 'bored'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['TED.com aç', 'İlgi alanına göre bir konuşma seç', 'Rahat otur', 'İlham al'],
    safetyNotes: null,
    url: 'https://www.ted.com',
  },
  {
    title: 'Manga/Çizgi Roman Oku',
    category: 'entertainment',
    tags: ['manga', 'çizgi roman', 'okuma'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'relaxed', 'happy'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Okuyacağın seriyi seç', 'Rahat bir pozisyon al', 'Atıştırmalık hazırla', 'Okumaya dal'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Aromaterapi / Mum Yak',
    category: 'wellness',
    tags: ['aromaterapi', 'mum', 'rahatlama'],
    durationMin: 15,
    durationMax: 60,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'anxious', 'relaxed'],
    location: Location.home,
    cost: Cost.low,
    social: Social.solo,
    steps: ['Kokulu mumunu seç', 'Odayı karart', 'Hafif müzik aç', 'Rahatla ve anın tadını çıkar'],
    safetyNotes: 'Mumu gözetimsiz bırakma',
    url: null,
  },

  // MEDIUM ENERGY - HOME
  {
    title: 'Tatlı/Kurabiye Yap',
    category: 'cooking',
    tags: ['tatlı', 'kurabiye', 'fırın'],
    durationMin: 45,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'bored', 'happy'],
    location: Location.home,
    cost: Cost.low,
    social: Social.both,
    steps: ['Tarif seç', 'Malzemeleri ölç', 'Hamuru hazırla', 'Fırına ver ve bekle'],
    safetyNotes: 'Fırın eldiveni kullan',
    url: null,
  },
  {
    title: 'Origami / El İşi',
    category: 'art',
    tags: ['origami', 'el işi', 'yaratıcılık'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'relaxed', 'focused'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Kağıt ve malzeme hazırla', 'YouTube\'dan tutorial seç', 'Adımları takip et', 'Eserini sergile'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Masa/Kart Oyunu Oyna',
    category: 'entertainment',
    tags: ['masa oyunu', 'kart', 'sosyal'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['bored', 'social', 'competitive'],
    location: Location.home,
    cost: Cost.free,
    social: Social.friends,
    steps: ['Oyun seç', 'Masayı hazırla', 'Kuralları oku', 'Oyuna başla'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Gardırop Düzenleme',
    category: 'productivity',
    tags: ['düzen', 'gardırop', 'organizasyon'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['productive', 'energetic', 'bored'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Tüm kıyafetleri çıkar', 'Giymediğin/eskimiş olanları ayır', 'Kategorilere göre düzenle', 'Bağışlanacakları ayır'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Blog/Hikaye Yaz',
    category: 'hobby',
    tags: ['yazma', 'blog', 'yaratıcılık'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'thoughtful', 'motivated'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Konu belirle', 'Taslak oluştur', 'Yazmaya başla', 'Gözden geçir ve düzenle'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'DIY Ev Dekorasyon',
    category: 'art',
    tags: ['dekorasyon', 'diy', 'yaratıcılık'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'productive', 'bored'],
    location: Location.home,
    cost: Cost.low,
    social: Social.solo,
    steps: ['Pinterest\'ten ilham al', 'Malzemeleri topla', 'Projeye başla', 'Eserini odana yerleştir'],
    safetyNotes: null,
    url: null,
  },

  // HIGH ENERGY - HOME
  {
    title: 'Vücut Ağırlığı Antrenmanı',
    category: 'fitness',
    tags: ['egzersiz', 'vücut ağırlığı', 'güç'],
    durationMin: 20,
    durationMax: 45,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'motivated', 'stressed'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Spor kıyafetlerini giy', 'Alan aç', 'Isınma yap', 'Şınav, squat, plank setlerine başla'],
    safetyNotes: 'Düzgün form koru',
    url: null,
  },
  {
    title: 'Zumba / Dans Dersi',
    category: 'fitness',
    tags: ['zumba', 'dans', 'kardiyo'],
    durationMin: 20,
    durationMax: 60,
    energyLevel: EnergyLevel.high,
    moodTags: ['happy', 'energetic', 'motivated'],
    location: Location.home,
    cost: Cost.free,
    social: Social.both,
    steps: ['YouTube\'dan zumba videosu bul', 'Rahat kıyafet giy', 'Salonda alan aç', 'Müziğe eşlik et'],
    safetyNotes: 'Isınma yap, su iç',
    url: null,
  },
  {
    title: 'İp Atlama',
    category: 'fitness',
    tags: ['ip atlama', 'kardiyo', 'egzersiz'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'stressed', 'motivated'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['İp al', 'Uygun alan bul', 'Isınma yap', '30 sn atla, 15 sn dinlen şeklinde tekrarla'],
    safetyNotes: 'Düzgün ayakkabı giy',
    url: null,
  },
  {
    title: 'Büyük Temizlik & Reorganizasyon',
    category: 'productivity',
    tags: ['temizlik', 'reorganizasyon', 'düzen'],
    durationMin: 60,
    durationMax: 180,
    energyLevel: EnergyLevel.high,
    moodTags: ['productive', 'energetic', 'motivated'],
    location: Location.home,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Hedef odayı belirle', 'Her şeyi çıkar', 'Temizle ve sil', 'Yeniden düzenle'],
    safetyNotes: null,
    url: null,
  },

  // LOW ENERGY - OUTDOOR
  {
    title: 'Sahilde/Göl Kenarında Otur',
    category: 'outdoor',
    tags: ['doğa', 'sahil', 'rahatlama'],
    durationMin: 20,
    durationMax: 90,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'relaxed', 'thoughtful'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Yakın bir sahil/göl bul', 'Battaniye veya havlu al', 'Otur ve manzarayı izle', 'Derin nefes al'],
    safetyNotes: 'Güneş kremi sür',
    url: null,
  },
  {
    title: 'Kitapçı/Kütüphane Gezisi',
    category: 'education',
    tags: ['kitap', 'kütüphane', 'keşif'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.low,
    moodTags: ['curious', 'bored', 'relaxed'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Yakındaki kitapçıya/kütüphaneye git', 'Rafları gez', 'İlgini çeken kitapları incele', 'Birini seç ve oku'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Sokak Sanatı Keşfet',
    category: 'culture',
    tags: ['sokak sanatı', 'graffiti', 'keşif'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.low,
    moodTags: ['creative', 'bored', 'curious'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.both,
    steps: ['Sokak sanatının yoğun olduğu bir semt seç', 'Yürüyerek keşfet', 'Fotoğraf çek', 'Favorilerini paylaş'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Pazar/Bit Pazarı Gez',
    category: 'shopping',
    tags: ['pazar', 'alışveriş', 'keşif'],
    durationMin: 30,
    durationMax: 120,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'curious', 'social'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Yakındaki pazarı bul', 'Tezgahları gez', 'İlginç şeyler keşfet', 'Pazarlık yap'],
    safetyNotes: null,
    url: null,
  },

  // MEDIUM ENERGY - OUTDOOR
  {
    title: 'Mini Golf',
    category: 'entertainment',
    tags: ['mini golf', 'eğlence', 'spor'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['bored', 'social', 'happy'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Mini golf alanı bul', 'Ekipman al', 'Parkuru gez', 'En az vuruşla bitirmeye çalış'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Karaoke',
    category: 'entertainment',
    tags: ['karaoke', 'müzik', 'eğlence'],
    durationMin: 60,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['happy', 'social', 'excited'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.friends,
    steps: ['Karaoke mekanı bul', 'Oda rezervasyonu yap', 'Şarkı listesi hazırla', 'Sahneye çık!'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Sokak Yemeği Turu',
    category: 'cooking',
    tags: ['sokak yemeği', 'yemek', 'keşif'],
    durationMin: 45,
    durationMax: 120,
    energyLevel: EnergyLevel.medium,
    moodTags: ['hungry', 'bored', 'adventurous'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Sokak yemeği bölgesini seç', 'Farklı tezgahlardan dene', 'Favorini bul', 'Fotoğraf çekmeyi unutma'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Hayvanat Bahçesi/Akvaryum',
    category: 'outdoor',
    tags: ['hayvanlar', 'doğa', 'keşif'],
    durationMin: 60,
    durationMax: 180,
    energyLevel: EnergyLevel.medium,
    moodTags: ['curious', 'bored', 'happy'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.both,
    steps: ['Bilet al', 'Rahat ayakkabı giy', 'Harita al', 'Hayvanları gözlemle ve öğren'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Tenis / Badminton',
    category: 'sports',
    tags: ['tenis', 'badminton', 'raket'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.medium,
    moodTags: ['energetic', 'competitive', 'bored'],
    location: Location.outdoor,
    cost: Cost.low,
    social: Social.friends,
    steps: ['Raket ve top al', 'Kort/alan bul', 'Isınma yap', 'Oynamaya başla'],
    safetyNotes: 'Isınma yap',
    url: null,
  },

  // HIGH ENERGY - OUTDOOR
  {
    title: 'Paintball / Lazer Tag',
    category: 'adventure',
    tags: ['paintball', 'lazer tag', 'macera'],
    durationMin: 60,
    durationMax: 120,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'excited', 'competitive'],
    location: Location.outdoor,
    cost: Cost.medium,
    social: Social.friends,
    steps: ['Mekanı bul ve rezervasyon yap', 'Uygun kıyafet giy', 'Ekipmanı tak', 'Takım kur ve savaş!'],
    safetyNotes: 'Güvenlik ekipmanını çıkarma',
    url: null,
  },
  {
    title: 'Go-Kart',
    category: 'adventure',
    tags: ['go-kart', 'yarış', 'heyecan'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.high,
    moodTags: ['excited', 'competitive', 'energetic'],
    location: Location.outdoor,
    cost: Cost.medium,
    social: Social.both,
    steps: ['Go-kart pistini bul', 'Bilet al', 'Güvenlik brifingi al', 'Yarışa başla!'],
    safetyNotes: 'Emniyet kemerini tak, kaskı çıkarma',
    url: null,
  },
  {
    title: 'Plaj Voleybolu',
    category: 'sports',
    tags: ['voleybol', 'plaj', 'takım'],
    durationMin: 30,
    durationMax: 90,
    energyLevel: EnergyLevel.high,
    moodTags: ['energetic', 'social', 'happy'],
    location: Location.outdoor,
    cost: Cost.free,
    social: Social.friends,
    steps: ['Top al', 'Sahilde uygun alan bul', 'Takım kur', 'Oyna!'],
    safetyNotes: 'Güneş kremi sür, su iç',
    url: null,
  },

  // ANY LOCATION
  {
    title: 'Müzik Dinle & Keşfet',
    category: 'music',
    tags: ['müzik', 'keşif', 'dinleme'],
    durationMin: 10,
    durationMax: 45,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'relaxed', 'happy'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Kulaklıklarını tak', 'Yeni tür/sanatçı keşfet', 'Beğendiklerini kaydet', 'Müziğin keyfini çıkar'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Farkındalık Egzersizi',
    category: 'wellness',
    tags: ['mindfulness', 'farkındalık', 'rahatlama'],
    durationMin: 5,
    durationMax: 20,
    energyLevel: EnergyLevel.low,
    moodTags: ['stressed', 'anxious', 'tired'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Gözlerini kapat', '5 duyunu sırayla fark et', 'Her birini isimlendir', 'Şu ana odaklan'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Hafıza / Beyin Oyunları',
    category: 'puzzle',
    tags: ['hafıza', 'beyin', 'zeka'],
    durationMin: 10,
    durationMax: 30,
    energyLevel: EnergyLevel.low,
    moodTags: ['bored', 'focused', 'curious'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Beyin oyunu uygulaması aç', 'Günlük antrenmanı seç', 'Odaklan ve çöz', 'Skorunu takip et'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Sketch / Doodle Çiz',
    category: 'art',
    tags: ['çizim', 'doodle', 'yaratıcılık'],
    durationMin: 10,
    durationMax: 45,
    energyLevel: EnergyLevel.low,
    moodTags: ['creative', 'bored', 'relaxed'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Kalem ve kağıt al', 'Aklına geleni çiz', 'Detaylarla oyna', 'Sonucu paylaş'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Hedef/Hayal Listesi Yaz',
    category: 'productivity',
    tags: ['hedef', 'planlama', 'motivasyon'],
    durationMin: 15,
    durationMax: 45,
    energyLevel: EnergyLevel.low,
    moodTags: ['motivated', 'thoughtful', 'productive'],
    location: Location.any,
    cost: Cost.free,
    social: Social.solo,
    steps: ['Defter aç', 'Kısa vadeli hedeflerini yaz', 'Uzun vadeli hayallerini ekle', 'İlk adımları belirle'],
    safetyNotes: null,
    url: null,
  },
  {
    title: 'Podcast Kaydet / Ses Notu',
    category: 'hobby',
    tags: ['podcast', 'ses', 'yaratıcılık'],
    durationMin: 15,
    durationMax: 60,
    energyLevel: EnergyLevel.medium,
    moodTags: ['creative', 'motivated', 'thoughtful'],
    location: Location.any,
    cost: Cost.free,
    social: Social.both,
    steps: ['Konu belirle', 'Sessiz ortam bul', 'Telefonu kayıta al', 'Düşüncelerini anlat'],
    safetyNotes: null,
    url: null,
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing data
  await prisma.favorite.deleteMany();
  await prisma.decisionHistory.deleteMany();
  await prisma.activity.deleteMany();
  await prisma.user.deleteMany();

  // Seed activities
  for (const activity of activities) {
    await prisma.activity.create({
      data: activity,
    });
  }

  console.log(`✅ Created ${activities.length} activities`);
  console.log('🎉 Seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
